# Generated by Django 5.1.6 on 2026-08-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('unit', models.CharField(default='unidad', max_length=30, verbose_name='unidad')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio de venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'sku'), name='unique_product_sku_per_company')],
            },
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('unit', models.CharField(default='unidad', max_length=30, verbose_name='unidad')),
                ('standard_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo estandar')),
                ('is_perishable', models.BooleanField(default=False, verbose_name='perecedera')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'materia prima',
                'verbose_name_plural': 'materias primas',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'sku'), name='unique_raw_material_sku_per_company')],
            },
        ),
    ]
