# Generated by Django 5.1.6 on 2026-08-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('preparacion', 'En preparacion'), ('empacado', 'Empacado'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('parcial', 'Parcial'), ('pendiente', 'Pedido pendiente'), ('cancelado', 'Cancelado')], default='creado', max_length=30, verbose_name='estado')),
                ('priority', models.PositiveIntegerField(default=3, verbose_name='prioridad')),
                ('promised_date', models.DateField(blank=True, null=True, verbose_name='fecha prometida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='companies.company', verbose_name='empresa')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.customerorder', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'linea de pedido',
                'verbose_name_plural': 'lineas de pedido',
            },
        ),
        migrations.AddConstraint(
            model_name='customerorder',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_order_code_per_company'),
        ),
    ]
