# Generated by Django 5.1.6 on 2026-08-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('ordenada', 'Ordenada'), ('recibida_parcial', 'Recibida parcial'), ('recibida', 'Recibida'), ('cancelada', 'Cancelada')], default='ordenada', max_length=30, verbose_name='estado')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='fecha de orden')),
                ('expected_receipt_date', models.DateField(blank=True, null=True, verbose_name='fecha esperada')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='fecha de recepcion')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='companies.company', verbose_name='empresa')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='proveedor')),
            ],
            options={
                'verbose_name': 'orden de compra',
                'verbose_name_plural': 'ordenes de compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo unitario')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder', verbose_name='orden de compra')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='products.rawmaterial', verbose_name='materia prima')),
            ],
            options={
                'verbose_name': 'linea de orden de compra',
                'verbose_name_plural': 'lineas de orden de compra',
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_purchase_code_per_company'),
        ),
    ]
