# Generated by Django 5.1.6 on 2026-08-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=40, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='companies.company', verbose_name='empresa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOM',
                'ordering': ['product__name', 'version'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_unit', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='cantidad por unidad')),
                ('scrap_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='merma porcentual')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.billofmaterials', verbose_name='BOM')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_lines', to='products.rawmaterial', verbose_name='materia prima')),
            ],
            options={
                'verbose_name': 'linea de BOM',
                'verbose_name_plural': 'lineas de BOM',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('status', models.CharField(choices=[('planificada', 'Planificada'), ('liberada', 'Liberada'), ('en_espera', 'En espera'), ('en_proceso', 'En proceso'), ('pausada', 'Pausada'), ('terminada', 'Terminada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='planificada', max_length=30, verbose_name='estado')),
                ('strategy', models.CharField(choices=[('make_to_stock', 'Make to Stock'), ('make_to_order', 'Make to Order'), ('assemble_to_order', 'Assemble to Order')], default='make_to_stock', max_length=30, verbose_name='estrategia')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='inicio planificado')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='fin planificado')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='fin real')),
                ('waste_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='merma')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costo estimado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.billofmaterials', verbose_name='BOM')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'orden de produccion',
                'verbose_name_plural': 'ordenes de produccion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('daily_capacity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='capacidad diaria')),
                ('labor_cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo hora mano de obra')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_centers', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'centro de trabajo',
                'verbose_name_plural': 'centros de trabajo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='nombre')),
                ('hourly_capacity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='capacidad por hora')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='production.workcenter', verbose_name='centro de trabajo')),
            ],
            options={
                'verbose_name': 'maquina',
                'verbose_name_plural': 'maquinas',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='billofmaterials',
            constraint=models.UniqueConstraint(fields=('company', 'product', 'version'), name='unique_bom_version_per_product'),
        ),
        migrations.AddConstraint(
            model_name='productionorder',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_production_code_per_company'),
        ),
    ]
