# Generated by Django 5.1.6 on 2026-08-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('segment', models.CharField(max_length=120, verbose_name='segmento')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='pais')),
                ('expected_service_level', models.PositiveIntegerField(default=95, verbose_name='nivel de servicio esperado')),
                ('payment_terms', models.CharField(blank=True, max_length=120, verbose_name='condiciones de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_customer_name_per_company')],
            },
        ),
    ]
