# Generated by Django 5.1.6 on 2026-08-06 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de empresa',
                'verbose_name_plural': 'tipos de empresa',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('country', models.CharField(default='Colombia', max_length=100, verbose_name='pais')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('currency', models.CharField(default='COP', max_length=10, verbose_name='moneda')),
                ('target_market', models.CharField(max_length=180, verbose_name='mercado objetivo')),
                ('plants_count', models.PositiveIntegerField(default=1, verbose_name='numero de plantas')),
                ('warehouses_count', models.PositiveIntegerField(default=1, verbose_name='numero de almacenes')),
                ('distribution_centers_count', models.PositiveIntegerField(default=0, verbose_name='centros de distribucion')),
                ('initial_capacity', models.PositiveIntegerField(default=100, verbose_name='capacidad inicial')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='capital inicial')),
                ('difficulty', models.CharField(choices=[('basico', 'Basico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='basico', max_length=20, verbose_name='nivel de dificultad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='estudiante')),
                ('company_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.companytype', verbose_name='tipo de empresa')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_company_name_per_owner')],
            },
        ),
    ]
