# Generated by Django 5.1.6 on 2026-08-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('gross_demand', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='demanda bruta')),
                ('planned_receipt_date', models.DateField(blank=True, null=True, verbose_name='fecha de recepcion planificada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_plans', to='companies.company', verbose_name='empresa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_plans', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'plan MRP',
                'verbose_name_plural': 'planes MRP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MRPLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_requirement', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='necesidad bruta')),
                ('available_inventory', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='inventario disponible')),
                ('scheduled_receipts', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='recepciones programadas')),
                ('net_requirement', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='necesidad neta')),
                ('planned_order_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='orden planificada')),
                ('release_offset_days', models.PositiveIntegerField(default=0, verbose_name='dias antes de liberar')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_lines', to='products.rawmaterial', verbose_name='materia prima')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mrp.mrpplan', verbose_name='plan MRP')),
            ],
            options={
                'verbose_name': 'linea MRP',
                'verbose_name_plural': 'lineas MRP',
                'ordering': ['raw_material__name'],
            },
        ),
    ]
