# Generated by Django 5.1.6 on 2026-08-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='capital inicial')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ingresos')),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costos')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='utilidad')),
                ('margin', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='margen')),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='flujo de caja')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_snapshots', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'resumen financiero',
                'verbose_name_plural': 'resumenes financieros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ingreso', 'Ingreso'), ('costo_compra', 'Costo de compra'), ('costo_produccion', 'Costo de produccion'), ('costo_almacenamiento', 'Costo de almacenamiento'), ('costo_transporte', 'Costo de transporte'), ('costo_devolucion', 'Costo de devolucion'), ('costo_faltante', 'Costo por faltante'), ('costo_mantenimiento', 'Costo de mantenimiento'), ('gasto_operativo', 'Gasto operativo'), ('penalizacion', 'Penalizacion')], max_length=40, verbose_name='categoria')),
                ('description', models.CharField(max_length=180, verbose_name='descripcion')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor')),
                ('transaction_date', models.DateField(verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'transaccion financiera',
                'verbose_name_plural': 'transacciones financieras',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
