# Generated by Django 5.1.6 on 2026-08-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('retraso_proveedor', 'Retraso de proveedor'), ('aumento_precios', 'Aumento de precios'), ('falla_maquinaria', 'Falla de maquinaria'), ('bloqueo_vias', 'Bloqueo de vias'), ('escasez_material', 'Escasez de materia prima'), ('aumento_demanda', 'Aumento inesperado de demanda'), ('caida_demanda', 'Caida de demanda'), ('problema_calidad', 'Problema de calidad'), ('clima', 'Evento climatico')], max_length=40, verbose_name='categoria')),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('probability', models.PositiveIntegerField(default=50, verbose_name='probabilidad porcentual')),
                ('impact', models.PositiveIntegerField(default=50, verbose_name='impacto porcentual')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('mitigado', 'Mitigado'), ('recuperado', 'Recuperado'), ('cerrado', 'Cerrado')], default='abierto', max_length=30, verbose_name='estado')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_events', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'evento de riesgo',
                'verbose_name_plural': 'eventos de riesgo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('prevencion', 'Prevencion'), ('mitigacion', 'Mitigacion'), ('respuesta', 'Respuesta'), ('recuperacion', 'Recuperacion')], max_length=30, verbose_name='estrategia')),
                ('action', models.TextField(verbose_name='accion')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo estimado')),
                ('effectiveness', models.PositiveIntegerField(default=50, verbose_name='efectividad porcentual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('risk_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='risks.riskevent', verbose_name='riesgo')),
            ],
            options={
                'verbose_name': 'respuesta de riesgo',
                'verbose_name_plural': 'respuestas de riesgo',
                'ordering': ['-created_at'],
            },
        ),
    ]
