# Generated by Django 5.1.6 on 2026-08-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, verbose_name='codigo')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('formula', models.TextField(verbose_name='formula')),
                ('result', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='resultado')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='unidad')),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='meta')),
                ('status', models.CharField(choices=[('bueno', 'Bueno'), ('advertencia', 'Advertencia'), ('critico', 'Critico')], max_length=30, verbose_name='estado')),
                ('traffic_light', models.CharField(choices=[('verde', 'Verde'), ('amarillo', 'Amarillo'), ('rojo', 'Rojo')], max_length=20, verbose_name='semaforo')),
                ('interpretation', models.TextField(verbose_name='interpretacion')),
                ('recommendation', models.TextField(verbose_name='recomendacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='companies.company', verbose_name='empresa')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='simulations.simulationperiod', verbose_name='periodo')),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='simulations.simulation', verbose_name='simulacion')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
                'ordering': ['name'],
            },
        ),
    ]
