# Generated by Django 5.1.6 on 2026-08-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('location', models.CharField(max_length=160, verbose_name='ubicacion')),
                ('currency', models.CharField(default='COP', max_length=10, verbose_name='moneda')),
                ('lead_time_days', models.PositiveIntegerField(default=7, verbose_name='lead time en dias')),
                ('reliability', models.PositiveIntegerField(default=90, verbose_name='confiabilidad porcentual')),
                ('quality_score', models.PositiveIntegerField(default=90, verbose_name='calidad porcentual')),
                ('payment_terms', models.CharField(blank=True, max_length=120, verbose_name='condiciones de pago')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad minima de pedido')),
                ('risk_level', models.CharField(default='Medio', max_length=80, verbose_name='nivel de riesgo')),
                ('certifications', models.CharField(blank=True, max_length=240, verbose_name='certificaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_supplier_name_per_company')],
            },
        ),
    ]
