# Generated by Django 5.1.6 on 2026-08-06 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='disponible')),
                ('quantity_committed', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comprometido')),
                ('quantity_in_transit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='en transito')),
                ('damaged_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='averiado')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='companies.company', verbose_name='empresa')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='products.rawmaterial', verbose_name='materia prima')),
            ],
            options={
                'verbose_name': 'item de inventario',
                'verbose_name_plural': 'items de inventario',
                'ordering': ['raw_material__name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('recepcion_compra', 'Recepcion de compra'), ('ajuste_entrada', 'Ajuste de entrada'), ('ajuste_salida', 'Ajuste de salida')], max_length=40, verbose_name='tipo')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo unitario')),
                ('reference', models.CharField(blank=True, max_length=120, verbose_name='referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='item de inventario')),
            ],
            options={
                'verbose_name': 'movimiento de inventario',
                'verbose_name_plural': 'movimientos de inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_demand', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='demanda anual')),
                ('ordering_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo de ordenar')),
                ('holding_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo anual de mantener')),
                ('daily_demand', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='demanda diaria')),
                ('lead_time_days', models.PositiveIntegerField(verbose_name='lead time en dias')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='stock de seguridad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_policies', to='companies.company', verbose_name='empresa')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_policies', to='products.rawmaterial', verbose_name='materia prima')),
            ],
            options={
                'verbose_name': 'politica de inventario',
                'verbose_name_plural': 'politicas de inventario',
                'ordering': ['raw_material__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('company', 'raw_material'), name='unique_inventory_item_per_material'),
        ),
        migrations.AddConstraint(
            model_name='inventorypolicy',
            constraint=models.UniqueConstraint(fields=('company', 'raw_material'), name='unique_inventory_policy_per_material'),
        ),
    ]
