# Generated by Django 5.1.6 on 2026-08-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.CharField(choices=[('recepcion_compra', 'Recepcion de compra'), ('consumo_produccion', 'Consumo de produccion'), ('ajuste_entrada', 'Ajuste de entrada'), ('ajuste_salida', 'Ajuste de salida')], max_length=40, verbose_name='tipo'),
        ),
    ]
