# Generated by Django 5.1.6 on 2026-08-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('scenario', models.CharField(default='Demanda estable', max_length=160, verbose_name='escenario')),
                ('total_periods', models.PositiveIntegerField(default=6, verbose_name='periodos totales')),
                ('periodicity', models.CharField(choices=[('dias', 'Dias'), ('semanas', 'Semanas'), ('meses', 'Meses'), ('trimestres', 'Trimestres')], default='meses', max_length=20, verbose_name='periodicidad')),
                ('status', models.CharField(choices=[('configuracion', 'Configuracion'), ('lista', 'Lista para iniciar'), ('en_curso', 'En curso'), ('periodo_abierto', 'Periodo abierto'), ('decisiones_registradas', 'Decisiones registradas'), ('procesando', 'Procesando'), ('periodo_cerrado', 'Periodo cerrado'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='periodo_abierto', max_length=40, verbose_name='estado')),
                ('current_period_number', models.PositiveIntegerField(default=1, verbose_name='periodo actual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'simulacion',
                'verbose_name_plural': 'simulaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='numero')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('decisiones_registradas', 'Decisiones registradas'), ('procesando', 'Procesando'), ('cerrado', 'Cerrado')], default='abierto', max_length=40, verbose_name='estado')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cierre')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='simulations.simulation', verbose_name='simulacion')),
            ],
            options={
                'verbose_name': 'periodo de simulacion',
                'verbose_name_plural': 'periodos de simulacion',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SimulationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('severity', models.CharField(choices=[('informativa', 'Informativa'), ('preventiva', 'Preventiva'), ('importante', 'Importante'), ('critica', 'Critica')], default='informativa', max_length=30, verbose_name='severidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='simulations.simulationperiod', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'evento de simulacion',
                'verbose_name_plural': 'eventos de simulacion',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PeriodResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_capital', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='capital disponible')),
                ('product_count', models.PositiveIntegerField(default=0, verbose_name='productos')),
                ('raw_material_count', models.PositiveIntegerField(default=0, verbose_name='materias primas')),
                ('supplier_count', models.PositiveIntegerField(default=0, verbose_name='proveedores')),
                ('customer_count', models.PositiveIntegerField(default=0, verbose_name='clientes')),
                ('decision_count', models.PositiveIntegerField(default=0, verbose_name='decisiones')),
                ('operational_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='puntaje operacional')),
                ('summary', models.TextField(verbose_name='resumen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='simulations.simulationperiod', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'resultado de periodo',
                'verbose_name_plural': 'resultados de periodo',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('general', 'General'), ('demanda', 'Demanda'), ('compras', 'Compras'), ('inventarios', 'Inventarios'), ('produccion', 'Produccion'), ('distribucion', 'Distribucion'), ('finanzas', 'Finanzas')], default='general', max_length=30, verbose_name='area')),
                ('title', models.CharField(max_length=160, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada')),
                ('locked', models.BooleanField(default=False, verbose_name='bloqueada')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='simulations.simulationperiod', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'decision',
                'verbose_name_plural': 'decisiones',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='simulationperiod',
            constraint=models.UniqueConstraint(fields=('simulation', 'number'), name='unique_period_number_per_simulation'),
        ),
    ]
