# Generated by Django 5.1.6 on 2026-08-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=30, verbose_name='placa')),
                ('weight_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='capacidad peso')),
                ('volume_capacity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='capacidad volumen')),
            ],
            options={
                'verbose_name': 'vehiculo',
                'verbose_name_plural': 'vehiculos',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('service_level', models.PositiveIntegerField(default=90, verbose_name='nivel de servicio')),
                ('cost_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo por km')),
                ('risk_level', models.CharField(default='Medio', max_length=80, verbose_name='nivel de riesgo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carriers', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'transportador',
                'verbose_name_plural': 'transportadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('origin_city', models.CharField(max_length=100, verbose_name='ciudad origen')),
                ('destination_city', models.CharField(max_length=100, verbose_name='ciudad destino')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='distancia km')),
                ('estimated_days', models.PositiveIntegerField(default=1, verbose_name='dias estimados')),
                ('risk_level', models.CharField(default='Medio', max_length=80, verbose_name='nivel de riesgo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('despachado', 'Despachado'), ('en_transito', 'En transito'), ('entregado', 'Entregado'), ('fallido', 'Entrega fallida'), ('cancelado', 'Cancelado')], default='despachado', max_length=30, verbose_name='estado')),
                ('dispatch_date', models.DateField(auto_now_add=True, verbose_name='fecha despacho')),
                ('delivered_date', models.DateField(blank=True, null=True, verbose_name='fecha entrega')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='costo de transporte')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='distribution.carrier', verbose_name='transportador')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'despacho',
                'verbose_name_plural': 'despachos',
                'ordering': ['-dispatch_date'],
            },
        ),
    ]
