# Generated by Django 5.1.6 on 2026-08-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SustainabilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(max_length=80, verbose_name='periodo')),
                ('energy_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='energia kWh')),
                ('water_m3', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='agua m3')),
                ('waste_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='residuos kg')),
                ('recovered_waste_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='residuos recuperados kg')),
                ('transport_emissions_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='emisiones transporte kg CO2e')),
                ('recycled_material_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='material reciclado porcentual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability_records', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'registro de sostenibilidad',
                'verbose_name_plural': 'registros de sostenibilidad',
                'ordering': ['-created_at'],
            },
        ),
    ]
