# Generated by Django 5.1.6 on 2026-08-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('inspected_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad inspeccionada')),
                ('conforming_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cantidad conforme')),
                ('nonconforming_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cantidad no conforme')),
                ('status', models.CharField(choices=[('planificada', 'Planificada'), ('completada', 'Completada'), ('rechazada', 'Rechazada')], default='completada', max_length=30, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='companies.company', verbose_name='empresa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_inspections', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'inspeccion de calidad',
                'verbose_name_plural': 'inspecciones de calidad',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NonConformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(max_length=140, verbose_name='tipo de defecto')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('root_cause', models.TextField(blank=True, verbose_name='causa raiz')),
                ('corrective_action', models.TextField(blank=True, verbose_name='accion correctiva')),
                ('status', models.CharField(choices=[('abierta', 'Abierta'), ('revision', 'En revision'), ('resuelta', 'Resuelta'), ('rechazada', 'Rechazada')], default='abierta', max_length=30, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonconformances', to='quality.qualityinspection', verbose_name='inspeccion')),
            ],
            options={
                'verbose_name': 'no conformidad',
                'verbose_name_plural': 'no conformidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('reason', models.CharField(max_length=180, verbose_name='motivo')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=30, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_complaints', to='companies.company', verbose_name='empresa')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='orders.customerorder', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='products.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'reclamo de cliente',
                'verbose_name_plural': 'reclamos de cliente',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='unique_complaint_code_per_company')],
            },
        ),
        migrations.AddConstraint(
            model_name='qualityinspection',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_quality_inspection_code_per_company'),
        ),
    ]
