# Generated by Django 5.1.6 on 2026-08-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('capacity_units', models.PositiveIntegerField(default=1000, verbose_name='capacidad en unidades')),
                ('is_distribution_center', models.BooleanField(default=False, verbose_name='centro de distribucion')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='companies.company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'almacen',
                'verbose_name_plural': 'almacenes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='disponible')),
                ('quantity_committed', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='comprometido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_stocks', to='products.product', verbose_name='producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_goods', to='warehouses.warehouse', verbose_name='almacen')),
            ],
            options={
                'verbose_name': 'stock de producto terminado',
                'verbose_name_plural': 'stock de producto terminado',
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('zone', models.CharField(blank=True, max_length=80, verbose_name='zona')),
                ('capacity_units', models.PositiveIntegerField(default=100, verbose_name='capacidad en unidades')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='warehouses.warehouse', verbose_name='almacen')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_warehouse_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='finishedgoodsstock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_finished_stock_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_location_code_per_warehouse'),
        ),
    ]
