# Generated by Django 5.1.6 on 2026-08-06 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_seed_company_types'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='codigo')),
                ('reason', models.CharField(max_length=180, verbose_name='motivo')),
                ('status', models.CharField(choices=[('solicitada', 'Solicitada'), ('autorizada', 'Autorizada'), ('recibida', 'Recibida'), ('inspeccionada', 'Inspeccionada'), ('dispuesta', 'Dispuesta'), ('rechazada', 'Rechazada'), ('cerrada', 'Cerrada')], default='solicitada', max_length=30, verbose_name='estado')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='solicitada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='companies.company', verbose_name='empresa')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='orders.customerorder', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'solicitud de devolucion',
                'verbose_name_plural': 'solicitudes de devolucion',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='cantidad')),
                ('condition', models.CharField(default='Pendiente de inspeccion', max_length=120, verbose_name='estado del producto')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='products.product', verbose_name='producto')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='reverse_logistics.returnrequest', verbose_name='devolucion')),
            ],
            options={
                'verbose_name': 'linea de devolucion',
                'verbose_name_plural': 'lineas de devolucion',
            },
        ),
        migrations.CreateModel(
            name='ReturnInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cantidad aceptada')),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='cantidad rechazada')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='reverse_logistics.returnrequest', verbose_name='devolucion')),
            ],
            options={
                'verbose_name': 'inspeccion de devolucion',
                'verbose_name_plural': 'inspecciones de devolucion',
            },
        ),
        migrations.CreateModel(
            name='DispositionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('reintegrar', 'Reintegrar al inventario'), ('reparar', 'Reparar'), ('reacondicionar', 'Reacondicionar'), ('reciclar', 'Reciclar'), ('reutilizar', 'Reutilizar'), ('disposicion_final', 'Disposicion final'), ('reembolso', 'Reembolso'), ('cambio', 'Cambio')], max_length=40, verbose_name='decision')),
                ('recovered_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor recuperado')),
                ('environmental_impact', models.CharField(blank=True, max_length=160, verbose_name='impacto ambiental')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositions', to='reverse_logistics.returnrequest', verbose_name='devolucion')),
            ],
            options={
                'verbose_name': 'decision de disposicion',
                'verbose_name_plural': 'decisiones de disposicion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='returnrequest',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_return_code_per_company'),
        ),
    ]
